service: random-voice-tinder
# app and org for use with dashboard.serverless.com
app: random-voice-tinder
org: minimarvin

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  hello:
    handler: handler.hello

# you can add CloudFormation resource templates here
resources:
  Resources:
    S3Audios:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: random-voice-tinder-audios
        Tags:
          - Key: service
            Value: random-voice-tinder
    DynamoUsers:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "random-voice-tinder-users"
        BillingMode: "PAY_PER_REQUEST"
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
          # - AttributeName: "name"
          #   AttributeType: "S"
          # - AttributeName: "chats"
          #   AttributeType: "SS"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        Tags:
          - Key: service
            Value: random-voice-tinder
    DynamoChats:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "random-voice-tinder-chats"
        BillingMode: "PAY_PER_REQUEST"
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
          - AttributeName: "updated_at"
            AttributeType: "S"
          # - AttributeName: "created_at"
          #   AttributeType: "S"
          # - AttributeName: "members"
          #   AttributeType: "SS"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
          - AttributeName: "updated_at"
            KeyType: "RANGE"
        Tags:
          - Key: service
            Value: random-voice-tinder
    DynamoMessages:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "random-voice-tinder-messages"
        BillingMode: "PAY_PER_REQUEST"
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
          - AttributeName: "created_at"
            AttributeType: "S"
          # - AttributeName: "chat_id"
          #   AttributeType: "SS"
          # - AttributeName: "sender_id"
          #   AttributeType: "S"
          # - AttributeName: "audio_message"
          #   AttributeType: "S"
          # - AttributeName: "time"
          #   AttributeType: "N"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
          - AttributeName: "created_at"
            KeyType: "RANGE"
        Tags:
          - Key: service
            Value: random-voice-tinder
